In [82]:
import numpy as np # 导入NumPy 模块

a = np.array([1.1, 2.2, 3.3], dtype=np.float64) # 指定 1 维数组的数值类型为 float64
a, a.dtype # 查看 a 及 dtype 类型

(array([1.1, 2.2, 3.3]), dtype('float64'))

In [2]:
a.astype(int).dtype # 将 a 的数值类型从 float64 转换为int, 并查看 dtype 类型

dtype('int32')

In [3]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array([(1, 2), (3, 4), (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# 在区间 [3, 7] 中以 0.5 为步长新建数组
np.arange(3, 7, 0.5, dtype='float32')

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

numpy.linspace(start, stop, num=50, endpoint=Ture, retstep=False, dtype=None)

start: 序列的起始值
stop: 序列的结束值
num: 生成的样本数，默认值为50
endpoint: 布尔值，如果为真，则最后一个样本包含在序列内
retstep: 布尔值，如果为真，返回间距
dtype: 数组的类型。

In [7]:
np.linspace(0, 10, 10, endpoint=True)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
# 将 endpoint 参数改成 False 看看区别
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

numpy.ones(shape, dtype=None, order='C'

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

numpy.zeros(shape, dtype=None, order='C')

In [10]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

eye 方法创建  
    numpy.eye(N, M=None, k=0, dtype=<type 'float'>)

In [11]:
np.eye(5, 4, 3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

从已知数据文件、函数中创建ndarry。NumPy提供了下面5个方法：

frombuffer (buffer) : 将缓冲区转换为 1 维数组，
fromfile (file, dtype, count, sep) : 从文本或二进制文件中构建多维数组，
fromfunction (function, shape) : 通过函数返回值来创建多维数组，
fromiter (iterable, dtype, count) : 从可迭代对象创建 1 维数组，
fromstring (string, dtype, count, sep) : 从字符串中创建 1 维数组。

In [12]:
np.fromfunction(lambda a, b: a + b, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a # 查看 a 的值

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ndarray.T 用于数组的转置， 与 .transpose() 相同

In [19]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

ndarray.dtype 用来输出数组包含元素的数据类型

In [20]:
a.dtype

dtype('int32')

ndarray.imag 用来输出数组包含元素的虚部

In [21]:
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

ndarray.real 用来输出数组包含元素的实部

In [22]:
a.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ndarray.size 用来输出数组中的总包含元素数

In [23]:
a.size

9

ndarray.itemsize 输出一个数组元素的字节数

In [25]:
a.itemsize

4

ndarray.nbytes 用来输出数组元素总字节数

In [26]:
a.nbytes

36

ndarray.ndim 用来输出数组尺寸

In [27]:
a.ndim

2

ndarray.shape 用来输出数组维数组

In [28]:
a.shape

(3, 3)

ndarray.strides 用来遍历数组时，输出每个维度中步进的字节数组

In [29]:
a.strides

(12, 4)

In [31]:
# 数组维度和形状
one = np.array([7, 2, 9, 10])
two = np.array([[5.2, 3.0, 4.5],
               [9.1, 0.1, 0.3]])
three = np.array([[[1, 1], [1, 1], [1, 1]],
                [[1, 1], [1, 1], [1, 1]],
                 [[1, 1], [1, 1], [1, 1]],
                 [[1, 1], [1, 1], [1, 1]]])

In [33]:
one.shape, two.shape, three.shape

((4,), (2, 3), (4, 3, 2))

重设形状
numpy.reshape(a, newshape)
其中， a 表示原数组，newshape 用于指定新的形状（整数或者元组）。

In [34]:
np.arange(10).reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

数组展开
numpy.ravel(a, order='C')

In [35]:
np.arange(10).reshape((2, 5))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.ravel(a, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

轴移动 moveaxis 可以将数组的轴移动到新的位置
numpy.moveaxis(a, source, destination)

a: 数组，
source: 要移动的轴的原始位置，
destination: 要移动的轴的目标位置。

In [38]:
a = np.ones((1, 2, 3))
np.moveaxis(a, 0, -1)

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [39]:
a.shape, np.moveaxis(a, 0, -1).shape

((1, 2, 3), (2, 3, 1))

轴交换
 和 moveaxis 不同的是， swapaxes 可以用来交换数组的轴。
 
 numpy.swapaxes(a, axisl, axis2)
  
  a: 数组，
  axisl: 需要交换的轴1位置，
  axis2: 需要与轴 1 交换位置的轴 1 位置。

In [40]:
a = np.ones((1, 4, 3))
np.swapaxes(a, 0, 2)

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

数组转置
 transpose 类似于矩阵的转置，它可以将 2 维数组的横轴和纵轴交换
 
  a: 数组，
  axis: 该值默认为 none, 表示转置。如果有值，那么则按照值替换轴

In [41]:
a = np.arange(4).reshape(2, 2)
np.transpose(a)

array([[0, 2],
       [1, 3]])

维度改变
 atleast_xd 支持将输入数据直接视为 x 维，这里的x 可以表示： 1， 2， 3
 
   numpy.atleast_1d()
   numpy.atleast_2d()
   numpy.atleast_3d()

In [43]:
print(np.atleast_1d([1, 2, 3]))
print(np.atleast_2d([4, 5, 6]))
print(np.atleast_3d([7, 8, 9]))

[1 2 3]
[[4 5 6]]
[[[7]
  [8]
  [9]]]


类型转换
 在 NumPy 中，还有一系列以 as 开头的方法，它们可以将特定输入转换为数组，亦可将数组转换为矩阵、标量，ndarry等
 
 asarray(a, dtype, order): 将特定输入转换为数组，
 asanyarry(a, dtype, order): 将特定输入转换为 ndarry,
 asmatrix(data, dtype): 将特定输入转换为矩阵，
 asfarray(a, dtype): 将特定输入转换为float 类型的数组，
 asarray_chkfinite(a, dtype, order): 将特定输入转换为数组，检查NaN 或 infs,
 asscalar(a): 将大小为 1 的数组转换为标量。

In [44]:
a = np.arange(4).reshape(2, 2)
np.asmatrix(a)  # 将二维数组转化为矩阵类型

matrix([[0, 1],
        [2, 3]])

数组连接
 concatenate 可以将多个数组沿指定轴连接在一起
  
 numpy.concatenate((a1, a2, ...), axis=0)
 
 (a1, a2, ...): 需要连接的数组，
 axis: 指定连接轴。

In [45]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10]])
c = np.array([[11, 12]])

np.concatenate((a, b, c), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8, 9,]])

np.concatenate((a, b.T), axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

数组堆叠
 在NumPy 中，以下方法可用于数组的堆叠：
 
 stack(arrays, axis): 沿着新轴连接数组的序列，
 colunm_stack(): 将 1 维数组作为列堆叠到 2 维数组中，
 hstack(): 按水平方向堆叠数组，
 vstack(): 按垂直方向堆叠数组，
 dstack(): 按深度方向堆叠数组。

In [50]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

拆分
 split 及与之相似的一系列方法主要是用于数组的拆分
 
 split(ary, indices_or_sections, axis): 将数组拆分为多个子数组，
 dsplit(ary, indices_or_sections): 按深度方向将数组拆分成多个子数组，
 hsplit(ary, indices_or_sections): 按水平方向将数组拆分成多个子数组，
 vsplit(ary, indices_or_sections): 按垂直方向将数组拆分成多个子数组。

In [52]:
a = np.arange(10)
np.split(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [53]:
a = np.arange(10).reshape(2, 5)
np.split(a, 2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

NumPy 中还有针对数组元素添加或移除的一些方法
  
  删除
  首先是delete 删除
  
  delete(arr, obj, axis): 沿特定轴删除数组中子数组

In [54]:
a = np.arange(12).reshape(3, 4)
np.delete(a, 2, 1)

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [55]:
np.delete(a, 2, 0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

数组插入
 再看一看insert插入，用法和 delete很相似，只是需要在第三个参数位置设置需要插入的数组对象：
 
 insert(arr, obj, values, axis): 依据索引在特定轴之前插入值

In [56]:
a = np.arange(12).reshape(3, 4)
b = np.arange(4)

np.insert(a, 2, b, 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

附加
 
  append 的用法也非常简单，只需要设置好需要附加的值和轴位置就好了，它其实相对于只能在末尾插入的insert, 所以少了一个指定索引的参数
  
  append(arr, values, axis):将值附加到数组的末尾，并返回 1 维数组。

In [57]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3)

np.append(a, b)
# 注意 append 方法返回值，默认是展平状态下的 1 维数组

array([0, 1, 2, 3, 4, 5, 0, 1, 2])

重设尺寸

 resize 就很好理解了，直接举例子吧：
  
  resize(a, new_shape): 对数组尺寸进行重新设定。

In [58]:
a = np.arange(10)
a.resize(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

翻转数组
 
  fliplr(m): 左右翻转数组，
  flipud(m): 上下翻转数组。

In [59]:
a = np.arange(16).reshape(4, 4)
print(np.fliplr(a))
print(np.flipud(a))

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


NumPy随机数

 NumPy的随机数功能非常强大，主要由 numpy.random 模块完成，
 
 首先，我们需要了解如何使用NumPy也就是生成一些满足基本需求的随机数据，主要由以下一些方法完成：
 
 numpy.random.rand(d0, d1, ..., dn) 方法的作用为：指定一个数组，并使用 [0,1] 区间随机数据填充，这些数据均匀分布。

In [63]:
np.random.rand(2, 5)

array([[0.11403927, 0.21932107, 0.76727445, 0.45606556, 0.38280459],
       [0.35473924, 0.05203464, 0.3825555 , 0.53027945, 0.31305944]])

numpy.random.rand(d0, d1, ..., dn) 与 numpy.random.rand(d0, d1, ..., dn) 的区别在于，前者是从标准正太分布中返回一个或多个样本值。

In [64]:
np.random.randn(1, 10)

array([[-0.6976546 ,  1.51554436,  0.67105875, -0.7495746 ,  0.61274015,
        -0.96783351, -1.3437705 , -1.71768977, -0.15703284,  1.97765577]])

randint(low, high, size, dtype) 方法将会生成[low, high] 的随机整数，注意这是一个半开半闭区间。

In [65]:
np.random.randint(2, 5, 10)

array([3, 2, 4, 3, 3, 4, 4, 3, 2, 2])

random_sample(size) 方法将会在 [0， 1] 区间内生成指定 size 的随机浮点数。

In [66]:
np.random.random_sample([10])

array([0.80801259, 0.33658538, 0.3857331 , 0.82156384, 0.51691333,
       0.43942203, 0.08406996, 0.19692194, 0.76842128, 0.20408077])

与 numpy.random.random_sample 类似的方法还有：
 
 numpy.random.random([size])
 numpy.random.ranf([size])
 numpy.random.sample([size])
 
 它们 4 个的效果都差不多
 
  choice(a, size, replace, p) 方法将会给定的数组里随机抽取几个值，该方法类似于随机抽样。

In [67]:
np.random.choice(10, 5)

# 上面的代码将会在 np.arange(10) 中随机抽取5个数。

array([7, 3, 1, 3, 5])

概率密度分布

 除了上面介绍的6种随机数生成方法， NumPy还提供了大量的满足特定概率密度分布的样本生成方法，它们的使用方法和上面非常相似，这里就不再一一介绍了。列举如下：    
    numpy.random.beta(a，b，size)：从 Beta 分布中生成随机数。
    numpy.random.binomial(n, p, size)：从二项分布中生成随机数。
    numpy.random.chisquare(df，size)：从卡方分布中生成随机数。
    numpy.random.dirichlet(alpha，size)：从 Dirichlet 分布中生成随机数。
    numpy.random.exponential(scale，size)：从指数分布中生成随机数。
    numpy.random.f(dfnum，dfden，size)：从 F 分布中生成随机数。
    numpy.random.gamma(shape，scale，size)：从 Gamma 分布中生成随机数。
    numpy.random.geometric(p，size)：从几何分布中生成随机数。
    numpy.random.gumbel(loc，scale，size)：从 Gumbel 分布中生成随机数。
    numpy.random.hypergeometric(ngood, nbad, nsample, size)：从超几何分布中生成随机数。
    numpy.random.laplace(loc，scale，size)：从拉普拉斯双指数分布中生成随机数。
    numpy.random.logistic(loc，scale，size)：从逻辑分布中生成随机数。
    numpy.random.lognormal(mean，sigma，size)：从对数正态分布中生成随机数。
    numpy.random.logseries(p，size)：从对数系列分布中生成随机数。
    numpy.random.multinomial(n，pvals，size)：从多项分布中生成随机数。
    numpy.random.multivariate_normal(mean, cov, size)：从多变量正态分布绘制随机样本。
    numpy.random.negative_binomial(n, p, size)：从负二项分布中生成随机数。
    numpy.random.noncentral_chisquare(df，nonc，size)：从非中心卡方分布中生成随机数。
    numpy.random.noncentral_f(dfnum, dfden, nonc, size)：从非中心 F 分布中抽取样本。
    numpy.random.normal(loc，scale，size)：从正态分布绘制随机样本。
    numpy.random.pareto(a，size)：从具有指定形状的 Pareto II 或 Lomax 分布中生成随机数。
    numpy.random.poisson(lam，size)：从泊松分布中生成随机数。
    numpy.random.power(a，size)：从具有正指数 a-1 的功率分布中在 0，1 中生成随机数。
    numpy.random.rayleigh(scale，size)：从瑞利分布中生成随机数。
    numpy.random.standard_cauchy(size)：从标准 Cauchy 分布中生成随机数。
    numpy.random.standard_exponential(size)：从标准指数分布中生成随机数。
    numpy.random.standard_gamma(shape，size)：从标准 Gamma 分布中生成随机数。
    numpy.random.standard_normal(size)：从标准正态分布中生成随机数。
    numpy.random.standard_t(df，size)：从具有 df 自由度的标准学生 t 分布中生成随机数。
    numpy.random.triangular(left，mode，right，size)：从三角分布中生成随机数。
    numpy.random.uniform(low，high，size)：从均匀分布中生成随机数。
    numpy.random.vonmises(mu，kappa，size)：从 von Mises 分布中生成随机数。
    numpy.random.wald(mean，scale，size)：从 Wald 或反高斯分布中生成随机数。
    numpy.random.weibull(a，size)：从威布尔分布中生成随机数。
    numpy.random.zipf(a，size)：从 Zipf 分布中生成随机数。

数学函数
 
使用Python 自带的运算符，你可以完成数学中的加减乘除，以及取余、取整，幂次计算等。导入自带的math 模块之后，里面又包含绝对值、
阶乘、开平方等一些常用的数学函数；不过，这些函数仍然相对基础，如果要完成更加复杂一些的数学计算，就会显得捉襟见付了。

NumPy为我们提供了更多的数学函数，以帮助我们更好地完成一些数值计算，下面就依次来看一看。

三角函数

首先，看一看NumPy提供的三角函数功能，这些方法有：

 numpy.sin(x): 三角正弦，
 numpy.cos(x): 三角余弦，
 numpy.tan(x): 三角正切，
 numpy.arcsin(x): 三角反正弦，
 numpy.arccos(x): 三角反余弦，
 numpy.arctan(x): 三角反正切，
 numpy.hypot(x1,x2): 直角三角形求斜边，
 numpy.degrees(x): 弧度转换为度，
 numpy.radians(x): 度转换为弧度，
 numpy.deg2rad(x): 度转换为弧度，
 numpy.fad2deg(x): 弧度转换为度。
 
 比如，我们可以用上面提到的 numpy.fad2deg(x): 弧度转换为度。

In [69]:
np.rad2deg(np.pi) # PI 值弧度表示

180.0

双曲函数
在数学中，双曲函数是一类与常见的三角函数类似的函数。双曲函数经常出现于某些重要的线性微分方程的解中，使用 NumPy 计算它们的方法为：
numpy.sinh(x)：双曲正弦。
numpy.cosh(x)：双曲余弦。
numpy.tanh(x)：双曲正切。
numpy.arcsinh(x)：反双曲正弦。
numpy.arccosh(x)：反双曲余弦。
numpy.arctanh(x)：反双曲正切。
数值修约
数值修约, 又称数字修约, 是指在进行具体的数字运算前, 按照一定的规则确定一致的位数, 然后舍去某些数字后面多余的尾数的过程。比如, 我们常听到的「4 舍 5 入」就属于数值修约中的一种。
numpy.around(a)：平均到给定的小数位数。
numpy.round_(a)：将数组舍入到给定的小数位数。
numpy.rint(x)：修约到最接近的整数。
numpy.fix(x, y)：向 0 舍入到最接近的整数。
numpy.floor(x)：返回输入的底部(标量 x 的底部是最大的整数 i)。
numpy.ceil(x)：返回输入的上限(标量 x 的底部是最小的整数 i).
numpy.trunc(x)：返回输入的截断值。


随机选择几个浮点数，看一看上面方法的区别。

In [71]:
a = np.random.randn(5) # 生成 5 个随机数
a  # 输出 a 的值

array([-0.55899671, -1.78346083, -1.99124314,  0.13107694, -1.3145877 ])

In [72]:
np.around(a)

array([-1., -2., -2.,  0., -1.])

In [73]:
np.rint(a)

array([-1., -2., -2.,  0., -1.])

In [74]:
np.fix(a)

array([-0., -1., -1.,  0., -1.])

求和、求积、差分
下面这些方法用于数组内元素或数组间进行求和、求积以及进行差分。
Markdown Code
    
 
numpy.prod(a, axis, dtype, keepdims)：返回指定轴上的数组元素的乘积。
numpy.sum(a, axis, dtype, keepdims)：返回指定轴上的数组元素的总和。
numpy.nanprod(a, axis, dtype, keepdims)：返回指定轴上的数组元素的乘积, 将 NaN 视作 1。
numpy.nansum(a, axis, dtype, keepdims)：返回指定轴上的数组元素的总和, 将 NaN 视作 0。
numpy.cumprod(a, axis, dtype)：返回沿给定轴的元素的累积乘积。
numpy.cumsum(a, axis, dtype)：返回沿给定轴的元素的累积总和。
numpy.nancumprod(a, axis, dtype)：返回沿给定轴的元素的累积乘积, 将 NaN 视作 1。
numpy.nancumsum(a, axis, dtype)：返回沿给定轴的元素的累积总和, 将 NaN 视作 0。
numpy.diff(a, n, axis)：计算沿指定轴的第 n 个离散差分。
numpy.ediff1d(ary, to_end, to_begin)：数组的连续元素之间的差异。
numpy.gradient(f)：返回 N 维数组的梯度。
numpy.cross(a, b, axisa, axisb, axisc, axis)：返回两个(数组）向量的叉积。
numpy.trapz(y, x, dx, axis)：使用复合梯形规则沿给定轴积分。


下面，我们选取几个举例测试一下：

In [75]:
a = np.arange(10)  # 生成0-9
a  # 输出 a 的值

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.sum(a)

45

In [77]:
np.diff(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

指数和对数
如果你需要进行指数或者对数求解，可以用到以下这些方法。
numpy.exp(x)：计算输入数组中所有元素的指数。
numpy.log(x)：计算自然对数。
numpy.log10(x)：计算常用对数。
numpy.log2(x)：计算二进制对数。


算术运算
当然，NumPy 也提供了一些用于算术运算的方法，使用起来会比 Python 提供的运算符灵活一些，主要是可以直接针对数组。
numpy.add(x1, x2)：对应元素相加。
numpy.reciprocal(x)：求倒数 1/x。
numpy.negative(x)：求对应负数。
numpy.multiply(x1, x2)：求解乘法。
numpy.divide(x1, x2)：相除 x1/x2。
numpy.power(x1, x2)：类似于 x1^x2。
numpy.subtract(x1, x2)：减法。
numpy.fmod(x1, x2)：返回除法的元素余项。
numpy.mod(x1, x2)：返回余项。
numpy.modf(x1)：返回数组的小数和整数部分。
numpy.remainder(x1, x2)：返回除法余数。

In [3]:
a1 = np.random.randint(0, 10, 5)  # 生成 5 个从 0-10 的随机整数
a2 = np.random.randint(0, 10, 5) 
a1, a2  # 输出 a1, a2

NameError: name 'np' is not defined

In [4]:
np.add(a1, a2)

NameError: name 'np' is not defined